
steps:
  #Docker Build
    - name: 'gcr.io/cloud-builders/docker'
    args: ["-c", "docker build --build-arg 'CONTAINER_PRIVATE_KEY=$$PRIVATE_KEY' --build-arg 'CONTAINER_PUBLIC_KEY=$$PUBLIC_KEY' -t gcr.io/${PROJECT_ID}/${_JOB_NAME}/my-docker-repo/myimage ."]
   images:
   -'gcr.io/noble-hydra-398406/github.com/nss55/cloud_deploy:$COMMIT_SHA'
  - dir: 'service/Dockerfile'

   # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/myimage']

   # Docker Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - 'run'
  - 'deploy'
  - 'cloudrunservice'
  - '--image'
  - 'gcr.io/noble-hydra-398406/github.com/nss55/cloud_deploy@sha256:a94e39ad839c6c3e0e6475ffb253283d76fcb0c13bcd8b0ea8e557d63ced2fa4'
  - '--region'
  - 'asia-east-1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--quiet'
    id: Deploy
    entrypoint: gcloud
  
  

