#timeout: 3600s
#options:
 # substitution_option: 'ALLOW_LOOSE'
  #machineType: 'E2_HIGHCPU_8'
  #dynamic_substitutions: true

substitutions:
 # _GCR_NM: hello-my-python
 # _SHORT_SHA: release_1.0
  _DOCKERFILE_PATH: hello-my-python/Dockerfile
  _DEPLOY_REGION: asia-east1

steps:
  #Docker Build
    - name: 'gcr.io/cloud-builders/docker'
    args: ["-c", "docker build --build-arg 'CONTAINER_PRIVATE_KEY=$$PRIVATE_KEY' --build-arg 'CONTAINER_PUBLIC_KEY=$$PUBLIC_KEY' -t gcr.io/${PROJECT_ID}/${_JOB_NAME} ."]
  
  
  
  
  
  
  
  
 # - name: 'python'
  #  args: ['build',
   #         '-t', 
    #        'gcr.io/${PROJECT_ID}/${_GCR_NM}:$_SHORT_SHA',
     #       '-f',
      #      '${_DOCKERFILE_PATH}',
       #     '.']
