steps:
  #Docker Build
   - name: 'gcr.io/cloud-builders/docker'
   args: ["-c", "docker build --build-arg 'CONTAINER_PRIVATE_KEY=$$PRIVATE_KEY' --build-arg 'CONTAINER_PUBLIC_KEY=$$PUBLIC_KEY' -t gcr.io/${PROJECT_ID}/${_JOB_NAME}/my-docker-repo/myimage ."]
  # images:
   #-'gcr.io/noble-hydra-398406/github.com/nss55/cloud_deploy:$COMMIT_SHA
   - dir: 'service/Dockerfile'
   # Docker Push
   - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 
           'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/myimage']
   # Docker Deploy container image to Cloud Run
   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
     args:
   - 'run',
   - 'deploy',
   - 'first_deploy',
   - '--image',
   - 'gcr.io/$PROJECT_ID/first_deploy:$COMMIT_SHA',
   - '--region',
   - 'asia-east-1',
   - '--platform',
   - 'managed',
   - '--allow-unauthenticated'
   images:
   - 'gcr.io/$PROJECT_ID/first_deploy:$COMMIT_SHA'
   entrypoint: gcloud
  

