#timeout: 3600s
#options:
 # substitution_option: 'ALLOW_LOOSE'
  #machineType: 'E2_HIGHCPU_8'
  #dynamic_substitutions: true

substitutions:
 # _GCR_NM: hello-my-python
 # _SHORT_SHA: release_1.0
  _DOCKERFILE_PATH: hello-my-python/Dockerfile
  _DEPLOY_REGION: asia-east1

steps:
  #Docker Build
    - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'asia-east1-docker.pkg.dev/${PROJECT_ID},'${_DOCKERFILE_PATH}',
           '.']
  
  
  
  
  
  
  
  
 # - name: 'python'
  #  args: ['build',
   #         '-t', 
    #        'gcr.io/${PROJECT_ID}/${_GCR_NM}:$_SHORT_SHA',
     #       '-f',
      #      '${_DOCKERFILE_PATH}',
       #     '.']
